name: tmp-test

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Install Xvfb
        run: sudo apt-get install xvfb

      - name: Run Test By Xvfb
        run: xvfb-run --auto-servernum npm run test
